name: MeinBulid

on:
  push:
    branches:
      - master

env:
  DOTNET_VERSION: '5.0.x'
  
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out code 🛎
        uses: actions/checkout@v2
      
      - name: Setup .NET 5 🔧
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Restore dependencies 🛠
        run: dotnet restore
          
      - name: Build app 🚀
        run: dotnet build -c Release --no-restore

      - name: Publish app 📰
        run: dotnet publish -c Release -o ./out
      - name: upload 
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: ./out 
